const FETCH_ALL_STORIES = "FETCH_ALL_STORIES";
const CREATE_STORY = "CREATE_STORY";
const UPDATE_STORY = "UPDATE_STORY";
const DELETE_STORY = "DELETE_STORY";
const LIKESTORY = "LIKESTORY";
const SIGNUP = "SIGNUP";
const LOGIN = "LOGIN";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

export { 
    FETCH_ALL_STORIES,  
    CREATE_STORY,
    UPDATE_STORY,
    DELETE_STORY,
    LIKESTORY,
    AUTHENTICATION,
    SIGNUP ,LOGIN,
    LOGOUT,
 }